"""
  disc1.py generated by WhatsOpt 1.25.1
"""
from .disc1_base import Disc1Base


class Disc1(Disc1Base):
    """A class to encapsulate Disc1 discipline"""

    def compute(self, inputs, outputs):
        """Disc1 computation"""
        # Here one can implement discipline resolution code
        # (python function or module, external software calls...)

        x = inputs["x"]  # shape: 1, type: Integer
        y2 = inputs["y2"]  # shape: 1, type: Float
        z = inputs["z"]  # shape: (2,), type: Float

        outputs["y1"] = z[0] ** 2 + z[1] + x - 0.2 * y2
