"""
  mda_init.py generated by WhatsOpt 1.25.1
"""
import numpy as np
from numpy import nan


def initialize(mda):
    mda["x"] = 2
    mda["z"] = [5, 2]
    return mda


if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, v] for k, v in mda.items()]
    print(tabulate(data, headers))
